default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <YOUR_DB_USER_NAME>
  password: <YOUR_DB_USER_PASSWORD>
  host: localhost
  port: 5432
  timeout: 5000

development: 
  <<: *default
  database: pdf_demo_app
